### ISSUE TITLE
Shard replica added before statefull set ready

### ISSUE THREAD

**Issue by AyWa** [zalando-incubator/es-operator#121]
## Expected Behavior

Shard replica should not be added, before node are ready.
As you can see in the actual behavior, because the EDS is updated ? I guess the existing operator get cancel, and restarted, but does not check for ready of the statefulsets
```
time="2020-09-24T09:00:52Z" level=error msg="Failed to operate resource: failed to rescale StatefulSet: StatefulSet es/data-id-id-v2 is not stable: 2/4 replicas ready"
```

## Actual Behavior

```
time="2020-09-24T09:00:52Z" level=info msg="Scaling hint: UP" eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Updating last scaling event in EDS 'es/data-id-id-v2'"
time="2020-09-24T09:00:52Z" level=info msg="Waiting for operation to stop" eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Terminating operator loop." eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Updating desired scaling for EDS 'es/data-id-id-v2'. New desired replicas: 4. Keeping shard-to-node ratio (1.00), and increasing index replicas."
time="2020-09-24T09:00:52Z" level=info msg="Waiting for operation to stop" eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Terminating operator loop." eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Event(v1.ObjectReference{Kind:\"ElasticsearchDataSet\", Namespace:\"es\", Name:\"data-id-id-v2\", UID:\"c63525d9-2b50-4b7d-9a34-102fed5c8327\", APIVersion:\"zalando.org/v1\", ResourceVersion:\"12281498\", FieldPath:\"\"}): type: 'Normal' reason: 'UpdatedStatefulSet' Updated StatefulSet 'es/data-id-id-v2'"
time="2020-09-24T09:00:52Z" level=info msg="Waiting for operation to stop" eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Event(v1.ObjectReference{Kind:\"ElasticsearchDataSet\", Namespace:\"es\", Name:\"data-id-id-v2\", UID:\"c63525d9-2b50-4b7d-9a34-102fed5c8327\", APIVersion:\"zalando.org/v1\", ResourceVersion:\"12281502\", FieldPath:\"\"}): type: 'Normal' reason: 'ChangingReplicas' Changing replicas 2 -> 4 for StatefulSet 'es/data-id-id-v2'"
time="2020-09-24T09:00:52Z" level=info msg="StatefulSet es/data-id-id-v2 has 2/4 ready replicas"
time="2020-09-24T09:00:52Z" level=error msg="Failed to operate resource: failed to rescale StatefulSet: StatefulSet es/data-id-id-v2 is not stable: 2/4 replicas ready"
time="2020-09-24T09:00:52Z" level=info msg="Terminating operator loop." eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Waiting for operation to stop" eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Setting number_of_replicas for index 'id_id_v2' to 1." endpoint="http://data-id-id-v2.es.svc.cluster.local.:9200"
time="2020-09-24T09:00:52Z" level=info msg="Terminating operator loop." eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Waiting for operation to stop" eds=data-id-id-v2 namespace=es
time="2020-09-24T09:00:52Z" level=info msg="Terminating operator loop." eds=data-id-id-v2 namespace=es
time="2020-09-24T09:01:22Z" level=info msg="Not scaling up, currently in cool-down period." eds=data-id-id-v2 namespace=es
```

## Steps to Reproduce the Problem

  1. Having an EDS with auto scaling enable (And set for example 1 max shards)
  1. Having a k8s without node ready to run a new ES pod
  1. create some load on the shard
  1. the operator will auto scaling -> but will skip the wait for "stable"  logic and replica will be created directly

## Specifications

  - Version: operator: 0.1.1, es: 7.9.0

**Comment by mikkeloscar** [comment]
From the issue it's not completely clear to me what the impact is of the shard replica being added before the ES node is ready. Can you elaborate on the impact? I.e. does ES go into a degraded state because of this?

**Comment by AyWa** [comment]
> From the issue it's not completely clear to me what the impact is of the shard replica being added before the ES node is ready. Can you elaborate on the impact? I.e. does ES go into a degraded state because of this?

Sure, so the impact of the replica being added before the ES node is mainly that it duplicate some shards operations (and so use more cpu / increase latency when cluster is really small), and also it is likely to go over the `max` shards per node that we set in the configuration

Lets make a simple example:
* 2 existing nodes with 1 shards each (no replica) (max shards 1)
* operator decide to auto scale because CPU is more than `50%`  (add 2 instance)
* Pod can take few minute to be ready
* the 2 existing nodes will send each other a shards
* New Node are ready. Need to wait for ES to re balance again the shards
* then shards are send to new node

If with the same configuration we wait for the node to be ready before creating the replica, we will not have a time where max shards is bigger than expected, and ES will likely move less shards.

Let me know if you need more information

**Comment by otrosien** [comment]
Hi @AyWa, I see your point. Unfortunately the timing of adding index replicas is hard to get right. If you do it too late ES would have started to relocate indices for no reason, and if you do it too early (as we're doing it now) it will be colocated on a n already crowded node, and then moved over. None of it is ideal. 

If you're in a lucky position to have single-shard indices, you might want to experiment with "index.auto_expand_replicas", this delegates the replica setting to ES.
