### ISSUE TITLE
Apply minIndexReplicas on config change

### ISSUE THREAD

**Issue by akryvko** [zalando-incubator/es-operator#141]
It looks like that the es-operator respects `minIndexReplicas` value only on auto scaling actions.
So there is no convenient way of setting desired index replicas count. 
This would be very useful for e.g. pre-scaling for some events. 
The `minIndexReplicas` parameter and maybe other parameters like `minShardsPerNode` could be applied also on config change.

**Comment by mikkeloscar** [comment]
Right now you should be able to "enable" autoscaling and just set min and max settings to the same value such that it can't autoscale. It's a bit of a hack, but could work as a workaround.

**Comment by akryvko** [comment]
Not sure that it will help. Let me describe the case:
- we had 12 pods and each index configured with 3 replicas, so `minIndexReplicas=3`
- since our traffic is very spiky we wanted to be prepared for morning peak by increasing pods count and index replicas beforehand. 
- so we updated pods to 18 and `minIndexReplicas=5`
- we expected that es-operator immediately change replica count right after configuration apply, but this not happened.
- so we had to manually update each index with  "number_of_replicas" : 5 which is not quite convenient
- as we understood es operator applies `minIndexReplicas` only on "scale trigger", e.g. high cpu consumption. Which does not work for cases when we want to be pre-scaled.
So we do not mind to have autoscaling, but also it would be good to apply `minIndexReplicas` to all indices immediately using config. 

Here is our config:
https://github.bus.zalan.do/Phoenix/lounge-elasticsearch/blob/master/deploy/prod/apply/eds.yaml

**Comment by mikkeloscar** [comment]
@akryvko thanks for clarifying. I realized that we only do es node scaling without looking at CPU metrics, but we don't do any index scaling without considering the CPU metrics, even when the config has changed.

I would consider this a bug (probably we didn't implement it as it wasn't needed in the past).

**Comment by otrosien** [comment]
Closed via #157. Thank you for the contribution.
