### ISSUE TITLE
Release the first version of es-operator

### ISSUE THREAD

**Issue by njuettner** [zalando-incubator/es-operator#17]
Release the first version of es-operator.

**Comment by otrosien** [comment]
Proposals for a version number? Do we follow semantic versioning?

**Comment by hjacobs** [comment]
Waiting for the release as Docker image :raised_hands:

Maybe start with v0.1?

**Comment by hjacobs** [comment]
Is this version supposed to work?

```
docker run -it registry.opensource.zalan.do/poirot/es-operator:master-8 --help
```

**Comment by otrosien** [comment]
yes. We're already publishing images, but we haven't released a tag yet.

**Comment by otrosien** [comment]
Done. https://github.com/zalando-incubator/es-operator/releases/tag/v0.1.0
