### ISSUE TITLE
Unable to create "Persistent Volume Claims"

### ISSUE THREAD

**Issue by kurtulusmengukan** [zalando-incubator/es-operator#170]
I am having trouble creating "Persistent Volume Claims". I request your support
 
Probably related to "volumeClaimTemplates" in "org_elasticsearchdatasets.yaml". Can you check ?

Exception Message:
create Claim -es-data-simple-0 for Pod es-data-simple-0 in StatefulSet es-data-simple failed error: PersistentVolumeClaim "-es-data-simple-0" is invalid: metadata.name: Invalid value: "-es-data-simple-0": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character

<img width="782" alt="Screen Shot 2021-04-30 at 01 08 08" src="https://user-images.githubusercontent.com/5060275/116624415-8d6ada00-a950-11eb-913a-d12366319020.png">

**Comment by otrosien** [comment]
Hello @kurtulusmengukan, can you paste the complete manifest?

**Comment by kurtulusmengukan** [comment]
Hi @otrosien,
I tried the steps in this [link](https://github.com/zalando-incubator/es-operator/blob/master/docs/GETTING_STARTED.md).
I just run the "docs/elasticsearchdataset-vct.yaml" file in the "Add Elasticsearch Data Sets" step.

I have not made any changes to yaml files

**Comment by otrosien** [comment]
I have no idea where this additional dash in the beginning is coming from. @mikkeloscar are you able to check this?
