### ISSUE TITLE
Elasticsearch data pods don't come up

### ISSUE THREAD

**Issue by talonx** [zalando-incubator/es-operator#242]
## Expected Behavior
ElasticsearchDataSet data pod should show up

## Actual Behavior
No data pods show up in any form, including pending.

## Steps to Reproduce the Problem

  1. Follow the instructions in https://github.com/zalando-incubator/es-operator/blob/master/docs/GETTING_STARTED.md

I started facing this in a new GKE cluster I had brought up. So I went back to the examples in your docs to rule out any issues with my config and they also don't work. The master pod comes up fine. The data pods don't show up.

## Specifications

  - Version: 0.1.3
  - Platform: GKE 1.20.12-gke.1500
  - Subsystem:

The operator logs have nothing helpful except for this line 
```
time="2022-03-07T09:50:12Z" level=error msg="Failed to operate resource: failed to ensure resources: failed to create PodDisruptionBudget for ElasticsearchDataSet elastic/es-data-simple: the server could not find the requested resource"
```
which seems like an effect rather than the cause.

**Comment by talonx** [comment]
Note that I have deployed the operator in a namespace called "elastic" and also modified all the other resources to deploy to this same namespace.

**Comment by talonx** [comment]
I figured out that the problem lies in the image. The operator deployment uses the latest tag which seems to have issues. I pinned the version to a sha that I am using in another K8S cluster (where things work) and it worked. In general I think it's not a good practice to use latest especially when your yamls, helm charts etc are all versioned. FWIW, the sha that worked is `registry.opensource.zalan.do/poirot/es-operator@sha256:7bc0fa0961feff7faa9adbd39e9b15338484e0f16af8525a474dc75a2e00b618` - this is probably pretty old as I had deployed it last year.

**Comment by mikkeloscar** [comment]
Could you share the full log of the latest version operator which fails. Without the context it's hard to understand what is going on.

**Comment by talonx** [comment]
@mikkeloscar I don't have the logs anymore. Anyway, I mentioned the root cause in my previous comments. I think that should be sufficient information to replicate and debug this.

**Comment by mikkeloscar** [comment]
I understand that the latest version fails for you, but doesn't help us understand why. We run e2e test on every change, so at least in the test environment it doesn't fail or our e2e environment doesn't cover your use case. Having the logs from the failure in your environment would help debug the root of the issue.

**Comment by talonx** [comment]
Unfortunately, I don't have the logs anymore.

**Comment by otrosien** [comment]
Without further details, it's not possible to debug your issue. Please re-open with logs attached if you run into similar issues again.
