### ISSUE TITLE
Could it be used with the eck operator?

### ISSUE THREAD

**Issue by sangkyunkim89** [zalando-incubator/es-operator#275]
Currently, I am using the eck operator to configure k8s. But eck is a paid version of autoscaling, so I want to use it. Can I use it together?

**Comment by otrosien** [comment]
Hey sangkyunkim89,

ECK and the ES-Operator are completely different stacks which don't interoperate at all. You could try to implement something yourself, but publishing software that would circumvent paid features will very likely put you into problematic waters.
