### ISSUE TITLE
Auto-scaling does not work with Opensearch

### ISSUE THREAD

**Issue by ngoctuyennguyen-epi** [zalando-incubator/es-operator#287]
## Expected Behavior
  The `es-data` pod can be scaled when the number of shards per node exceeds `maxShardsPerNode` 

## Actual Behavior
   I got the below error message, and the `es-data` pod can't be scaled when the number of shards per node exceeds `maxShardsPerNode`

```
time="2022-08-29T10:27:16Z" level=info msg="Scaling hint: DOWN" eds=es-data namespace=default
panic: assignment to entry in nil map

goroutine 26 [running]:
github.com/zalando-incubator/es-operator/operator.(*ElasticsearchOperator).scaleEDS(0xc00020fcb0, {0x183f2d0, 0xc0003ea0c0}, 0xc0005b2380, 0x0?, 0x1?)
	/workspace/operator/elasticsearch.go:860 +0x52d
github.com/zalando-incubator/es-operator/operator.(*ElasticsearchOperator).runAutoscaler(0xc00020fcb0, {0x183f2d0, 0xc0003ea0c0})
	/workspace/operator/elasticsearch.go:242 +0x33c
created by github.com/zalando-incubator/es-operator/operator.(*ElasticsearchOperator).Run
	/workspace/operator/elasticsearch.go:93 +0x105
```

## Steps to Reproduce the Problem
   I tried to apply these `yaml` files (https://github.com/zalando-incubator/es-operator/tree/master/docs) following the README

## Specifications

  - Version: `1.24.3`
  - Platform: `AKS`
  - Subsystem: [Flux2](https://github.com/fluxcd/flux2)

**Comment by otrosien** [comment]
Hey @ngoctuyennguyen-epi, we never claimed compatibility with OpenSearch. For this, please take a look at https://github.com/Opster/opensearch-k8s-operator

**Comment by ngoctuyennguyen-epi** [comment]
Hi @otrosien, 
It's my mistake when typing. I tried testing with Elasticsearch and got this issue

**Comment by juntezhang** [comment]
> Hey @ngoctuyennguyen-epi, we never claimed compatibility with OpenSearch. For this, please take a look at https://github.com/Opster/opensearch-k8s-operator

Hi @otrosien we are getting this issue as well on Elasticsearch 7.10.2. The operator is working fine on Flux1 but after upgrading to Flux2, the auto-scaling stopped working.  Could you perhaps help us in finding the root cause for this issue? We suspect there are some breaking changes in Flux2 compared to Flux2. The exception that @ngoctuyennguyen-epi posted indicates that the operator is not able to list the data nodes.
