### ISSUE TITLE
Using Zalando's ScalingSchedule to Scale EDS Instances

### ISSUE THREAD

**Issue by A-Kamaee** [zalando-incubator/es-operator#365]
I came across Zalando's [ScalingSchedule feature](https://github.com/zalando-incubator/kube-metrics-adapter/tree/master#scalingschedule-collectors) and it caught my interest. I would like to understand if it's feasible to leverage this feature to scale my EDS instances.

If someone has experience using this or can provide guidance on its compatibility with EDS, I would greatly appreciate it.

Thanks!

**Comment by mikkeloscar** [comment]
Unfortunately this is not supported at the moment. There was some work last year to get it integrated, but we never finished that https://github.com/zalando-incubator/es-operator/pull/276

**Comment by A-Kamaee** [comment]
Thank you for the update. Our team could greatly benefit from this feature, so I'll be sure to follow up on it.
