### ISSUE TITLE
Elasticsearch v7.0 support

### ISSUE THREAD

**Issue by rimusz** [zalando-incubator/es-operator#41]
Does it support Elasticsearch v7.0?

**Comment by otrosien** [comment]
We haven't tested it yet, but yes, theoretically it should. Are you planning to upgrade from 6 to 7 in a rolling fashion or is it a new deployment?

**Comment by rimusz** [comment]
just the new deployment with v7.0.0 we are looking for :)
where do I need to specify the version?

**Comment by rimusz** [comment]
I don't see an option to change ES version in https://github.com/zalando-incubator/es-operator/tree/master/manifests

**Comment by rimusz** [comment]
no worries, found it https://github.com/zalando-incubator/es-operator/blob/master/docs/elasticsearch-cluster.yaml#L67

**Comment by otrosien** [comment]
yep, just give it a try and report back if it works for you.

**Comment by otrosien** [comment]
@rimusz I gave ES 7 a spin. It works, but the cluster bootstrapping changed a bit because of the new zen protocol. You can take a look here for the changes needed: https://github.com/zalando-incubator/es-operator/pull/44
